services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: tu_clave
      POSTGRES_DB: tu_base_de_datos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: tu_usuario_mongo
      MONGO_INITDB_ROOT_PASSWORD: tu_clave_mongo
      MONGO_INITDB_DATABASE: tu_base_de_mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5433
      DB_USER: tu_usuario
      DB_PASS: tu_clave
      DB_NAME: tu_base_de_datos
      MONGO_HOST: mongo
      MONGO_PORT: 27018
      MONGO_USER: tu_usuario_mongo
      MONGO_PASS: tu_clave_mongo
      MONGO_NAME: tu_base_de_mongo
      LEVEL_LOG_CONSOLE: debug
    depends_on:
      - postgres
      - mongo
    command: npm start

volumes:
  postgres_data:
  mongo_data:
